import {
  MessageSquare,
  PenLine,
  Image as ImageIcon,
  FileText,
  Mail,
  Search,
  Code2,
  Languages,
  SpellCheck2,
  FileSearch,
  ListChecks,
  FolderOpen,
  Mic,
  ClipboardList,
  Megaphone,
  Briefcase,
  ShoppingBag,
  LayoutTemplate,
  BadgeDollarSign,
} from "lucide-react";
import type { ToolDefinition } from "@/types/tools";

export const tools: ToolDefinition[] = [
  { slug: "chat", title: "AI chat assistant", description: "Ask anything, get instant answers", icon: MessageSquare, category: "productivity", available: true },
  { slug: "content-writer", title: "Content writer", description: "Blog posts, articles, and more", icon: PenLine, category: "writing", available: false },
  { slug: "image-generator", title: "Image generator", description: "Create images from text prompts", icon: ImageIcon, category: "media", available: false },
  { slug: "resume-builder", title: "Resume builder", description: "Build a polished resume fast", icon: FileText, category: "writing", available: false },
  { slug: "email-writer", title: "Email writer", description: "Professional emails in seconds", icon: Mail, category: "writing", available: false },
  { slug: "seo-writer", title: "SEO writer", description: "Search-optimized copy", icon: Search, category: "writing", available: false },
  { slug: "code-generator", title: "Code generator", description: "Generate and explain code", icon: Code2, category: "code", available: false },
  { slug: "translator", title: "Translator", description: "Translate between languages", icon: Languages, category: "writing", available: false },
  { slug: "grammar-fixer", title: "Grammar fixer", description: "Clean up grammar and tone", icon: SpellCheck2, category: "writing", available: false },
  { slug: "humanizer", title: "Humanizer", description: "Make AI text sound natural", icon: PenLine, category: "writing", available: false },
  { slug: "summarizer", title: "Summarizer", description: "Condense long text fast", icon: ListChecks, category: "productivity", available: false },
  { slug: "document-analyzer", title: "Document analyzer", description: "Extract insights from documents", icon: FileSearch, category: "productivity", available: false },
  { slug: "pdf-chat", title: "PDF chat", description: "Ask questions about a PDF", icon: FolderOpen, category: "productivity", available: false },
  { slug: "meeting-notes", title: "Meeting notes", description: "Turn recordings into notes", icon: Mic, category: "productivity", available: false },
  { slug: "social-media", title: "Social media generator", description: "Posts for every platform", icon: Megaphone, category: "writing", available: false },
  { slug: "business-plan", title: "Business plan generator", description: "Structured business plans", icon: Briefcase, category: "writing", available: false },
  { slug: "product-description", title: "Product description", description: "Compelling product copy", icon: ShoppingBag, category: "writing", available: false },
  { slug: "landing-page", title: "Landing page generator", description: "Copy for landing pages", icon: LayoutTemplate, category: "writing", available: false },
  { slug: "ad-copy", title: "Ad copy generator", description: "High-converting ad copy", icon: BadgeDollarSign, category: "writing", available: false },
  { slug: "prompt-library", title: "Prompt library", description: "Curated prompts to get started", icon: ClipboardList, category: "productivity", available: false },
];